### ISSUE TITLE
开始进入页面时的分类，是可以作为参数传给ChatGPT服务器的？

### ISSUE THREAD

**Issue by guotong1988** [youking-lib/ai-assistant#1]
<img width="308" alt="image" src="https://user-images.githubusercontent.com/4702353/218387390-f00aed95-c5a5-41fe-8fae-4f1912217a89.png">

多谢多谢！@youking-lib

**Comment by guotong1988** [comment]
哦，好像不是作为参数传的


https://github.com/youking-lib/ai-assistant/tree/main/scripts

**Comment by youking-lib** [comment]
@guotong1988  这是 [awesome-chatgpt-prompts](https://github.com/f/awesome-chatgpt-prompts) 仓库收集的 prompts，调用 OpenAI 服务作为入参即可
