### ISSUE TITLE
support ChatGPTUnofficialProxyAPI 

### ISSUE THREAD

**Issue by yiios** [youking-lib/ai-assistant#7]
Currently, we are using the text-davinci-003 model provided by OpenAI, which is mainly used for writing and has poor conversational ability and mostly no contextual ability.
It is hoped that ChatGPTUnofficialProxyAPI will be supported as soon as possible to make the experience of ai-assistant and ChatGPT web consistent.

**Comment by yiios** [comment]
generate OpenAI access token : https://github.com/rhaym-tech/AIKey

**Comment by youking-lib** [comment]
Now, support uses the gpt-3.5-turbo-0301 model with the official OpenAI chat completions API (official, robust approach, but it's not free)

https://platform.openai.com/docs/guides/chat
