### ISSUE TITLE
prompt and context invailded after chatgpt 5.0.x

### ISSUE THREAD

**Issue by JellyBo** [youking-lib/ai-assistant#9]
chatgpt依赖升级到5.0版本后默认使用gpt-3.5-turbo聊天模型，接口和出入参均与此前的接口有区别，因此目前版本的角色提示语和上下文不再生效。

https://platform.openai.com/docs/api-reference/chat

<img width="1512" alt="截屏2023-03-04 21 19 01" src="https://user-images.githubusercontent.com/9100842/222904186-e5ebaa35-2672-4848-974f-b7bdff3dc69b.png">

**Comment by youking-lib** [comment]
I have fixed it, thank you for your feedback.
